# Generated by Django 2.1.4 on 2019-01-06 07:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('wanikani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecharacter',
            name='definitions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=400, size=None),
        ),
    ]
