# Generated by Django 2.1.4 on 2019-01-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanikani', '0002_auto_20190106_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecharacter',
            name='user_level',
            field=models.IntegerField(default=0),
        ),
    ]
