# Generated by Django 2.1.4 on 2019-01-22 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wanikani', '0002_auto_20190121_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_correct_pinyin', models.IntegerField(default=0)),
                ('num_correct_definitions', models.IntegerField(default=0)),
                ('num_correct_all', models.IntegerField(default=0)),
                ('num_times_shown', models.IntegerField(default=0)),
                ('unlocked_date', models.DateTimeField(default=None)),
                ('upcoming_review_date', models.DateTimeField(default=None)),
                ('last_reviewed_date', models.DateTimeField(default=None)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanikani.BaseCharacter')),
                ('last_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wanikani.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanikani.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='levelcharacter',
            name='character',
        ),
        migrations.RemoveField(
            model_name='levelcharacter',
            name='last_session',
        ),
        migrations.RemoveField(
            model_name='levelcharacter',
            name='user',
        ),
        migrations.DeleteModel(
            name='LevelCharacter',
        ),
    ]
