# Generated by Django 2.1.4 on 2019-01-12 23:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanikani', '0003_basecharacter_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecharacter',
            name='definitions',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='basecharacter',
            name='pinyin',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='characters',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
