# Generated by Django 2.1.4 on 2019-01-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanikani', '0004_auto_20190122_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresscharacter',
            name='last_reviewed_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
