# Generated by Django 2.1.4 on 2019-01-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanikani', '0005_auto_20190126_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresscharacter',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
