# Generated by Django 2.1.4 on 2019-01-27 17:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanikani', '0006_progresscharacter_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresscharacter',
            name='num_correct_all',
        ),
        migrations.RemoveField(
            model_name='progresscharacter',
            name='num_correct_definitions',
        ),
        migrations.RemoveField(
            model_name='progresscharacter',
            name='num_correct_pinyin',
        ),
        migrations.AddField(
            model_name='progresscharacter',
            name='num_correct',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'all': 0, 'definitions': 0, 'pinyin': 0}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progresscharacter',
            name='num_current_incorrect',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'definitions': 0, 'pinyin': 0}),
            preserve_default=False,
        ),
    ]
