# Generated by Django 2.1.4 on 2019-02-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanikani', '0008_user_last_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresscharacter',
            name='last_correct',
            field=models.BooleanField(default=False),
        ),
    ]
