# Generated by Django 2.1.4 on 2019-02-23 06:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanikani', '0009_progresscharacter_last_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresscharacter',
            name='synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
